// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBsb_sxkch0wLuyz2tCNN1Rk3We987qQM',
    appId: '1:762913908028:web:284a15602ebd315afa2a39',
    messagingSenderId: '762913908028',
    projectId: 'trendhub-f1b7a',
    authDomain: 'trendhub-f1b7a.firebaseapp.com',
    storageBucket: 'trendhub-f1b7a.appspot.com',
    measurementId: 'G-PS6S32Z8LZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0nzc_aGHzSiMJHEDiM74EmX0mj6bcfqM',
    appId: '1:762913908028:android:1b634f8bbb6badcefa2a39',
    messagingSenderId: '762913908028',
    projectId: 'trendhub-f1b7a',
    storageBucket: 'trendhub-f1b7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdtP8rminyQSa3eTOxaHZnB_-yDeVTKuk',
    appId: '1:762913908028:ios:5d0a19ef928ab243fa2a39',
    messagingSenderId: '762913908028',
    projectId: 'trendhub-f1b7a',
    storageBucket: 'trendhub-f1b7a.appspot.com',
    iosBundleId: 'com.example.trendhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdtP8rminyQSa3eTOxaHZnB_-yDeVTKuk',
    appId: '1:762913908028:ios:fca5f283851e2511fa2a39',
    messagingSenderId: '762913908028',
    projectId: 'trendhub-f1b7a',
    storageBucket: 'trendhub-f1b7a.appspot.com',
    iosBundleId: 'com.example.trendhub.RunnerTests',
  );
}
